### ISSUE TITLE
PlatformName : Linux doesnt work for android

### ISSUE THREAD

**Issue by Dharin-shah** [appium/appium-geckodriver#11]
https://discuss.appium.io/t/firefox-for-appium-android-not-running-on-linux/33247

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/pull/15183 should fix that

**Comment by sparsh00** [comment]
@mykola-mokhnach I tried your fix and its still giving error. I am running `appium 1.20.2` with `geckodriver 0.29.0` and `firefox 80.1.1`

**Comment by mykola-mokhnach** [comment]
> I am running appium 1.20.2

@sparsh00 did you run appium from my branch?

**Comment by sparsh00** [comment]
> @sparsh00 did you run appium from my branch?
I modified appium 1.20.2 locally

**Comment by mykola-mokhnach** [comment]
It won't work. the source needs to be transpiled first. Or you need to modify stuff inside of `build` folder instead and restart the server to pick up changes

**Comment by sparsh00** [comment]
Did that, forgot mentioning getting geckodriver error. Can it be due to firefox version? Attaching trace
[firefox_appium_github.log](https://github.com/appium/appium-geckodriver/files/6124382/firefox_appium_github.log)

**Comment by mykola-mokhnach** [comment]
Yeah, this is something wrong in the geckodriver itself. nothing we could do from Appium side.
